DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS item_request CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    is_available BOOLEAN,
    owner_id     BIGINT                                  NOT NULL,
    request_id BIGINT
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    item_id    BIGINT                                  NOT NULL,
    booker_id  BIGINT                                  NOT NULL,
    status VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS item_request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    requester_id BIGINT,
    created TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(1024)                           NOT NULL,
    item_id   BIGINT                                  NOT NULL,
    author_id BIGINT                                  NOT NULL,
    created TIMESTAMP NOT NULL
);

ALTER TABLE users
    ADD CONSTRAINT PK_USER PRIMARY KEY (id),
    ADD CONSTRAINT UQ_USER_EMAIL UNIQUE (email);

ALTER TABLE item_request
    ADD CONSTRAINT PK_ITEM_REQUEST PRIMARY KEY (id),
    ADD CONSTRAINT FK_ITEM_REQUEST_FOR_REQUESTER FOREIGN KEY (requester_id) REFERENCES users (id);

ALTER TABLE items
    ADD CONSTRAINT PK_ITEM PRIMARY KEY (id),
    ADD CONSTRAINT FK_ITEM_FOR_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    ADD CONSTRAINT FK_ITEM_FOR_REQUEST FOREIGN KEY (request_id) REFERENCES item_request (id) ON DELETE CASCADE;

ALTER TABLE bookings
    ADD CONSTRAINT PK_BOOKING PRIMARY KEY (id),
    ADD CONSTRAINT FK_BOOKING_FOR_BOOKER FOREIGN KEY (booker_id) REFERENCES users (id),
    ADD CONSTRAINT FK_BOOKING_FOR_ITEM FOREIGN KEY (item_id) REFERENCES items (id);


ALTER TABLE comments
    ADD CONSTRAINT PK_COMMENTS PRIMARY KEY (id),
    ADD CONSTRAINT FK_COMMENT_FOR_ITEM FOREIGN KEY (item_id) REFERENCES items (id),
    ADD CONSTRAINT FK_COMMENT_FOR_USER FOREIGN KEY (author_id) REFERENCES users (id);

